### ISSUE TITLE
build-container-image should include the full dockerfile name

### ISSUE THREAD

**Issue by shay-stratoscale** [Stratoscale/skipper#46]
Today the build-container-image contains only a part of the dockerfile name and assumes it starts with 'Dockerfile.' prefix. it's confusing and counter intuitive

**Comment by adir-stratoscale** [comment]
@shay-stratoscale what do you think about the following suggestion:
the default dockerfile for an image (every image not necessarily the build container image) will be the Dockerfile.{image-name}. if you want to use different dockerfile for an image, you will have to specify it in the config file.
```yaml
images:
    - foo-image: Dockerfile.bar
    - some-image: Dockerfile
    - another-image: cool-image.Dockerfile
```

@eran-stratoscale @rom-stratoscale @ravid-stratoscale - fyi
